sudo: required

language: generic

services:
  - docker

before_install:
  - docker login -u="$DOCKERUSER" -p="$DOCKERPASS"
  - docker pull jgontrum/spacyapi:latest
  - docker pull jgontrum/spacyapi:de

install:
  - docker build -t jgontrum/spacyapi:base --cache-from jgontrum/spacyapi:latest .
  - docker build -t jgontrum/spacyapi:en -f docker/en/Dockerfile --cache-from jgontrum/spacyapi:latest .
  - docker tag jgontrum/spacyapi:en jgontrum/spacyapi:latest
  - docker build -t jgontrum/spacyapi:de -f docker/de/Dockerfile --cache-from jgontrum/spacyapi:de .

after_success:
  - docker push jgontrum/spacyapi:base
  - docker push jgontrum/spacyapi:en
  - docker push jgontrum/spacyapi:latest
  - docker push jgontrum/spacyapi:de
# TODO: Add other languages
