sudo: required

language: generic

services:
  - docker

before_install:
  - docker login -u="$DOCKERUSER" -p="$DOCKERPASS"

install:
  - docker build -t jgontrum/spacyapi:base_v2 .
  - docker build -t jgontrum/spacyapi:en_v2 -f docker/en/Dockerfile .
  - docker build -t jgontrum/spacyapi:de_v2 -f docker/de/Dockerfile .
  - docker build -t jgontrum/spacyapi:es_v2 -f docker/es/Dockerfile .
  - docker build -t jgontrum/spacyapi:all_v2 -f docker/all/Dockerfile .

after_success:
  - docker push jgontrum/spacyapi:base_v2
  - docker push jgontrum/spacyapi:en_v2
  - docker push jgontrum/spacyapi:de_v2
  - docker push jgontrum/spacyapi:es_v2
  - docker push jgontrum/spacyapi:all_v2

